"""change bacref

Revision ID: 190acffb7f2a
Revises: be95685a674d
Create Date: 2018-11-20 09:22:23.823964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190acffb7f2a'
down_revision = 'be95685a674d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_review_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'review_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_review_id_fkey', 'users', 'pitches', ['review_id'], ['id'])
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###
